/*
 * Bundles the headless CLI (cmd/binary.ts) into a single Node executable.
 *
 * Unlike the plugin build (esbuild.config.mjs, platform=browser, obsidian
 * external), this targets Node and aliases `obsidian` to the Node shim so the
 * reused sync engine resolves against fs-backed stand-ins. Telemetry stays off
 * because the shipped code detects Node (`typeof window === "undefined"`).
 */

import esbuild from "esbuild";
import process from "process";
import { fileURLToPath } from "url";
import path from "path";
import { readFile } from "fs/promises";

const dirname = path.dirname(fileURLToPath(import.meta.url));
const prod = process.argv[2] === "production";

const pkg = JSON.parse(await readFile(path.join(dirname, "package.json"), "utf-8"));
const version = process.env.SYNCBUNDLEVERSION ?? pkg.version ?? "dev";

const banner = `#!/usr/bin/env node
/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD (headless CLI)
Source: https://github.com/parrajustin/obsidian-drive-sync (cmd/)
*/`;

await esbuild.build({
    banner: { js: banner },
    entryPoints: [path.join(dirname, "cmd/binary.ts")],
    bundle: true,
    platform: "node",
    format: "cjs",
    target: "node20",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    minify: prod,
    outfile: path.join(dirname, "dist-bin/drive-sync.cjs"),
    define: {
        "globalThis.SYNCBUNDLEVERSION": `"${version}"`,
        // Node build never ships telemetry regardless, but label it production.
        "globalThis.SYNCBUNDLEENV": `"production"`,
        "globalThis.LOKIACCESSCLIENTID": `""`,
        "globalThis.LOKIACCESSCLIENTSECRET": `""`,
        __BINARY_VERSION__: `"${version}"`
    },
    alias: {
        // Resolve the engine's `import ... from "obsidian"` to the Node shim.
        obsidian: path.join(dirname, "cmd/obsidian_shim.ts")
    }
});

process.stdout.write("Built dist-bin/drive-sync.cjs\n");
