on:
   push:
     branches:
       - main
name: release-please
permissions: {}
jobs:
  release-please:
    permissions:
      contents: write # to create release commit (google-github-actions/release-please-action)
      pull-requests: write # to create release PR (google-github-actions/release-please-action)

    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
    #   - uses: actions/checkout@v3

    #   - uses: pnpm/action-setup@v4
    #     name: Install pnpm
    #     with:
    #       version: 9
    #       run_install: false

    #   - name: Use Node.js
    #     uses: actions/setup-node@v3
    #     with:
    #       node-version: '21.x'
    #       cache: 'pnpm'

    #   - name: Install dependencies
    #     run: pnpm install

    #   - name: Build plugin
    #     run: npm run build

    #   - name: push plugin release
    #     run: |
    #       git config user.name github-actions[bot]
    #       git config user.email 41898282+github-actions[bot]@users.noreply.github.com
    #       git remote add gh-token "https://${{ secrets.GITHUB_TOKEN}}@github.com/parrajustin/obsidian-drive-sync.git"
    #       git checkout -b release
    #       git add -f dist
    #       git commit -a -m 'chore: ${{ steps.release.outputs.tag_name }} release'
    #       git push origin
    #       git tag -a ${{ steps.release.outputs.tag_name }} -m 'chore: ${{ steps.release.outputs.tag_name }} release'
    #       git push origin ${{ steps.release.outputs.tag_name }}
    #       gh release create "$tag" \
    #         --title="$tag" \
    #         dist/main.js manifest.json styles.css
    #     if: ${{ steps.release.outputs.release_created }}

    #   - name: Create release
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     run: |
    #       tag="${GITHUB_REF#refs/tags/}"

    #       gh release create "$tag" \
    #         --title="$tag" \
    #         dist/main.js manifest.json styles.css
